baseurl = "https://trax.chs.chalmers.se/"
title = "T-RAX Chalmers Makerspace"
languageCode = "en-us"
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Makerspace"
    identifier = "menu.makerspace"
    url        = "/makerspace/"
    weight     = 2

#[[menu.main]]
#    name       = "FUSE"
#    identifier = "menu.fuse"
#    url        = "/fuse/"
#    weight     = 3

[[menu.main]]
    name       = "Courses & Events"
    identifier = "menu.courses"
    url        = "/courses/"
    weight     = 4

[[menu.main]]
    name       = "About Us"
    identifier = "menu.about"
    url        = ""
    weight     = 5

[[menu.main]]
    name       = "The Board"
    parent     = "menu.about"
    identifier = "menu.the-board"
    url        = "/about/the-board"
    weight     = 1

[[menu.main]]
    name       = "Documents"
    parent     = "menu.about"
    identifier = "menu.docs"
    url        = "/about/docs"
    weight     = 2

[[menu.main]]
    name       = "Become a member"
    identifier = "menu.membership"
    url        = "/membership/"
    weight     = 8

[[menu.main]]
    name       = "FAQ"
    identifier = "menu.faq"
    url        = "/faq/"
    weight     = 9



[params]
    author = "kjeller"
 
    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "trax"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "T-RAX"

    logo = "img/logo/logo_color.png"
    # logo_small = "img/logo/logo-small.png"

[params.makerspace]
    # Control how many cards per row to display
    cards_per_row = 4

[params.docs]
    # Control how many cards per row to display
    cards_per_row = 3

[params.features]
    cols = 2
